version: 1.4.1.{build}
configuration:
  - Release
  - Debug
platform: Any CPU
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
nuget:
  disable_publish_on_pr: true
before_build:
- nuget restore
build:
  verbosity: minimal
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/7f66502fe0bc27f98a3d
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: Webhook
    url: https://webhooks.gitter.im/e/44a18139c91b1172a7b5
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
deploy:
 - provider: NuGet
   server: https://www.myget.org/F/gw2net/api/v2/package
   api_key:
     secure: V1Eie9yECoTRMNzKOu3mAjLrILfnVvgVUn2/tZFHBQn36Gto3dsnKuUmfwkKyOVv
   skip_symbols: false
   symbol_server: https://www.myget.org/F/gw2net/api/v2/package
   on:
     configuration: Debug
 - provider: NuGet
   server: https://www.myget.org/F/gw2net/api/v2/package
   api_key:
     secure: V1Eie9yECoTRMNzKOu3mAjLrILfnVvgVUn2/tZFHBQn36Gto3dsnKuUmfwkKyOVv
   skip_symbols: true
   on:
     configuration: Release
