version: 1.0.1.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
nuget:
  disable_publish_on_pr: true
before_build:
- nuget restore
build:
  verbosity: minimal
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/7f66502fe0bc27f98a3d
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
configuration: Release
platform: Any CPU
